//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public string class_id { get; set; }
        public string subject_id { get; set; }
        public string teacher_id { get; set; }
        public string class_code { get; set; }
        public string class_name { get; set; }
        public string date_from { get; set; }
        public string date_to { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
