//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class family_members
    {
        public string family_member_id { get; set; }
        public string family_id { get; set; }
        public string parent_or_student_member { get; set; }
        public string parent_id { get; set; }
        public string student_id { get; set; }
    }
}
