//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class address
{
    public string address_id { get; set; }
    public string address_detail { get; set; }
}

public partial class @class
{
    public string class_id { get; set; }
    public string subject_id { get; set; }
    public string teacher_id { get; set; }
    public string class_code { get; set; }
    public string class_name { get; set; }
    public string date_from { get; set; }
    public string date_to { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class family_members
{
    public string family_member_id { get; set; }
    public string family_id { get; set; }
    public string parent_or_student_member { get; set; }
    public string parent_id { get; set; }
    public string student_id { get; set; }
}

public partial class homework
{
    public string homework_id { get; set; }
    public string student_id { get; set; }
    public string date_created { get; set; }
    public string homework_content { get; set; }
    public string grade { get; set; }
    public string other_homework_details { get; set; }
}

public partial class parent
{
    public string parent_id { get; set; }
    public string gender { get; set; }
    public string first_name { get; set; }
    public string middle_name { get; set; }
    public string last_name { get; set; }
    public string other_parent_details { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class parent_addresses
{
    public string parent_id { get; set; }
    public string gender { get; set; }
    public string first_name { get; set; }
    public string middle_name { get; set; }
    public string last_name { get; set; }
    public string other_parent_details { get; set; }
}

public partial class report
{
    public string report_id { get; set; }
    public string student_id { get; set; }
    public string date_created { get; set; }
    public string report_content { get; set; }
    public string teacher_comments { get; set; }
    public string other_report_details { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public string first_name { get; set; }
    public string middle_name { get; set; }
    public string last_name { get; set; }
    public string gender { get; set; }
}

public partial class school
{
    public string school_id { get; set; }
    public string address_id { get; set; }
    public string school_name { get; set; }
    public string school_principal { get; set; }
    public string other_school_details { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class school_addresses
{
    public string address_id { get; set; }
    public string address_detail { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public string school_name { get; set; }
    public string img { get; set; }
    public string school_address { get; set; }
}

public partial class stdent_families
{
    public string family_id { get; set; }
    public string head_of_family_parent_id { get; set; }
    public string family_name { get; set; }
}

public partial class student
{
    public string student_id { get; set; }
    public string gender { get; set; }
    public string first_name { get; set; }
    public string middle_name { get; set; }
    public string last_name { get; set; }
    public Nullable<System.DateTime> date_of_birth { get; set; }
    public string other_student_details { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public string class_code { get; set; }
    public string address { get; set; }
    public string father_name { get; set; }
    public string mother_name { get; set; }
    public string admission_on { get; set; }
    public string school_name { get; set; }
    public string mobile_no { get; set; }
}

public partial class student_addresses
{
    public string student_id { get; set; }
    public string address_id { get; set; }
    public string date_from { get; set; }
    public string address_details { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class student_classes
{
    public string student_id { get; set; }
    public string class_id { get; set; }
    public string date_from { get; set; }
    public string date_to { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class student_parents
{
    public string student_id { get; set; }
    public string parent_id { get; set; }
}

public partial class subject
{
    public string subject_id { get; set; }
    public string subject_name { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class teacher
{
    public string teacher_id { get; set; }
    public string school_id { get; set; }
    public string gender { get; set; }
    public string first_name { get; set; }
    public string middle_name { get; set; }
    public string last_name { get; set; }
    public string other_teacher_details { get; set; }
    public Nullable<bool> IsActive { get; set; }
}
