//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class homework
    {
        public string homework_id { get; set; }
        public string student_id { get; set; }
        public string date_created { get; set; }
        public string homework_content { get; set; }
        public string grade { get; set; }
        public string other_homework_details { get; set; }
    }
}
