//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string student_id { get; set; }
        public string gender { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string other_student_details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string class_code { get; set; }
        public string address { get; set; }
        public string father_name { get; set; }
        public string mother_name { get; set; }
        public string admission_on { get; set; }
        public string school_name { get; set; }
        public string mobile_no { get; set; }
    }
}
